[plugin]
id = "ai-anthropic-compiler-plugin"
class = "io.ballerina.lib.ai.anthropic.AiAnthropicCompilerPlugin"

[[dependency]]
path = "../compiler-plugin/build/libs/ai.anthropic-compiler-plugin-1.1.2.jar"

[[dependency]]
path = "../compiler-plugin/build/libs/ballerina-to-openapi-2.3.0.jar"
