// Copyright (c) 2025 WSO2 LLC (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/ai;
import ballerina/ai.observe;
import ballerina/http;
import ballerina/jballerina.java;

const DEFAULT_ANTHROPIC_SERVICE_URL = "https://api.anthropic.com/v1";
const DEFAULT_MAX_TOKEN_COUNT = 512;
const DEFAULT_TEMPERATURE = 0.7d;
const ANTHROPIC_API_VERSION = "2023-06-01";

# Provider is a client class that provides an interface for interacting with Anthropic Large Language Models.
public isolated client class ModelProvider {
    *ai:ModelProvider;
    private final http:Client AnthropicClient;
    private final string apiKey;
    private final string modelType;
    private final int maxTokens;
    private final decimal temperature;

    # Initializes the Anthropic model with the given connection configuration and model configuration.
    #
    # + apiKey - The Anthropic API key
    # + modelType - The Anthropic model name
    # + apiVersion - The Anthropic API version (e.g., "2023-06-01")  
    # + serviceUrl - The base URL of Anthropic API endpoint
    # + maxTokens - The upper limit for the number of tokens in the response generated by the model
    # + temperature - The temperature for controlling randomness in the model's output  
    # + connectionConfig - Additional HTTP connection configuration
    # + return - `nil` on successful initialization; otherwise, returns an `ai:Error`
    public isolated function init(string apiKey,
            @display {label: "Model Type"} ANTHROPIC_MODEL_NAMES modelType,
            @display {label: "Service URL"} string serviceUrl = DEFAULT_ANTHROPIC_SERVICE_URL,
            @display {label: "Maximum Tokens"} int maxTokens = DEFAULT_MAX_TOKEN_COUNT,
            @display {label: "Temperature"} decimal temperature = DEFAULT_TEMPERATURE,
            @display {label: "Connection Configuration"} *ConnectionConfig connectionConfig) returns ai:Error? {

        // Convert ConnectionConfig to http:ClientConfiguration
        http:ClientConfiguration anthropicConfig = {
            httpVersion: connectionConfig.httpVersion,
            http1Settings: connectionConfig.http1Settings ?: {},
            http2Settings: connectionConfig?.http2Settings ?: {},
            timeout: connectionConfig.timeout,
            forwarded: connectionConfig.forwarded,
            poolConfig: connectionConfig?.poolConfig,
            cache: connectionConfig?.cache ?: {},
            compression: connectionConfig.compression,
            circuitBreaker: connectionConfig?.circuitBreaker,
            retryConfig: connectionConfig?.retryConfig,
            responseLimits: connectionConfig?.responseLimits ?: {},
            secureSocket: connectionConfig?.secureSocket,
            proxy: connectionConfig?.proxy,
            validation: connectionConfig.validation
        };

        http:Client|error httpClient = new http:Client(serviceUrl, anthropicConfig);
        if httpClient is error {
            return error ai:Error("Failed to initialize Anthropic Model", httpClient);
        }

        self.AnthropicClient = httpClient;
        self.apiKey = apiKey;
        self.modelType = modelType;
        self.maxTokens = maxTokens;
        self.temperature = temperature;
    }

    # Uses Anthropic API to generate a response
    # + messages - List of chat messages or a user message
    # + tools - Tool definitions to be used for the tool call
    # + stop - Stop sequence to stop the completion (not used in this implementation)
    # + return - Chat response or an error in case of failures
    isolated remote function chat(ai:ChatMessage[]|ai:ChatUserMessage messages, (ai:ChatCompletionFunctions|ai:BuiltInTool)[] tools = [], string? stop = ())
        returns ai:ChatAssistantMessage|ai:Error {
        observe:ChatSpan span = observe:createChatSpan(self.modelType);
        span.addProvider("anthropic");
        span.addTemperature(self.temperature);
        json|ai:Error inputMessage = convertMessageToJson(messages);
        if inputMessage is json {
            span.addInputMessages(inputMessage);
        }

        // Map messages to Anthropic format
        AnthropicMessage[]|ai:Error anthropicMessages = self.mapToAnthropicMessages(messages);
        if anthropicMessages is ai:Error {
            span.close(anthropicMessages);
            return anthropicMessages;
        }

        // Prepare request payload
        map<json> requestPayload = {
            model: self.modelType,
            max_tokens: self.maxTokens,
            messages: anthropicMessages,
            temperature: self.temperature
        };

        if stop is string {
            span.addStopSequence(stop);
            requestPayload["stop_sequences"] = [stop];
        }

        // If tools are provided, add them to the request
        if tools.length() > 0 {
            ai:ChatCompletionFunctions[] functionTools = [];
            ai:BuiltInTool[] builtInTools = [];
            foreach ai:ChatCompletionFunctions|ai:BuiltInTool tool in tools {
                if tool is ai:ChatCompletionFunctions {
                    functionTools.push(tool);
                } else {
                    builtInTools.push(tool);
                }
            }

            // Validate built-in tools — only web_search and code_execution are supported
            foreach ai:BuiltInTool builtInTool in builtInTools {
                if builtInTool !is CodeExecutionTool && builtInTool !is WebSearchTool {
                    ai:Error err = error ai:Error(string `Unsupported built-in tool: '${builtInTool.name}'. `
                        + "The Anthropic model provider currently only supports 'web_search' and 'code_execution' built-in tools.");
                    span.close(err);
                    return err;
                }
            }

            json[] toolsPayload = self.mapToAnthropicTools(functionTools);
            foreach ai:BuiltInTool builtInTool in builtInTools {
                json|ai:Error builtInToolJson = self.mapBuiltInToolToJson(builtInTool);
                if builtInToolJson is ai:Error {
                    span.close(builtInToolJson);
                    return builtInToolJson;
                }
                toolsPayload.push(builtInToolJson);
            }

            span.addTools(toolsPayload);
            requestPayload["tools"] = toolsPayload;
        }

        // Send request to Anthropic API with proper headers
        map<string> headers = {
            "x-api-key": self.apiKey,
            "anthropic-version": ANTHROPIC_API_VERSION,
            "content-type": "application/json"
        };

        AnthropicApiResponse|error anthropicResponse = self.AnthropicClient->/messages.post(requestPayload, headers);
        if anthropicResponse is error {
            ai:Error err = error ai:LlmInvalidResponseError("Unexpected response format from Anthropic API", anthropicResponse);
            span.close(err);
            return err;
        }

        span.addResponseId(anthropicResponse.id);
        span.addInputTokenCount(anthropicResponse.usage.input_tokens);
        span.addOutputTokenCount(anthropicResponse.usage.output_tokens);
        span.addFinishReason(anthropicResponse.stop_reason);

        ai:ChatAssistantMessage|ai:Error response = self.getAssistantMessage(anthropicResponse);
        if response is ai:Error {
            span.close(response);
            return response;
        }
        span.addOutputMessages(response);
        span.addOutputType(observe:TEXT);
        span.close();
        return response;
    }

    private isolated function getAssistantMessage(AnthropicApiResponse anthropicResponse) returns ai:ChatAssistantMessage|ai:Error {
        string? content = ();
        ai:FunctionCall[] toolCalls = [];
        foreach ContentBlock block in anthropicResponse.content {
            string blockType = block.'type;
            if blockType == "tool_use" {
                toolCalls.push(check mapContentToFunctionCall(block));
            } else if blockType == "text" {
                content = block.text;
            }
        }
        return {role: ai:ASSISTANT, toolCalls: toolCalls == [] ? () : toolCalls, content};
    }

    # Sends a chat request to the model and generates a value that belongs to the type
    # corresponding to the type descriptor argument.
    #
    # + prompt - The prompt to use in the chat messages
    # + td - Type descriptor specifying the expected return type format
    # + return - Generates a value that belongs to the type, or an error if generation fails
    isolated remote function generate(ai:Prompt prompt, @display {label: "Expected type"} typedesc<anydata> td = <>)
                    returns td|ai:Error = @java:Method {
        'class: "io.ballerina.lib.ai.anthropic.Generator"
    } external;

    # Converts standard ai:ChatMessage array to Anthropic's message format
    #
    # + messages - List of chat messages or a user message
    # + return - return value description
    private isolated function mapToAnthropicMessages(ai:ChatMessage[]|ai:ChatUserMessage messages)
    returns AnthropicMessage[]|ai:Error {
        AnthropicMessage[] anthropicMessages = [];
        if messages is ai:ChatUserMessage {
            anthropicMessages.push({
                role: ai:USER,
                content: check getChatMessageStringContent(messages.content)
            });
            return anthropicMessages;
        }

        foreach ai:ChatMessage message in messages {
            if message is ai:ChatUserMessage {
                anthropicMessages.push({
                    role: ai:USER,
                    content: check getChatMessageStringContent(message.content)
                });
            } else if message is ai:ChatSystemMessage {
                // Add a user message containing the system prompt
                string content = check getChatMessageStringContent(message.content);
                anthropicMessages.push({
                    role: ai:USER,
                    content: string `<system>${content}</system>\n\n`
                });
            } else if message is ai:ChatAssistantMessage && message.content is string {
                anthropicMessages.push({
                    role: ai:ASSISTANT,
                    content: message.content ?: ""
                });
            } else if message is ai:ChatFunctionMessage && message.content is string {
                // Include function results as user messages with special formatting
                anthropicMessages.push({
                    role: ai:USER,
                    content: string `<function_results>\nFunction: ${message.name}\n`
                        + string `Output: ${message.content ?: ""}\n</function_results>`
                });
            }
        }
        return anthropicMessages;
    }

    # Maps ai:ChatCompletionFunctions to Anthropic's tool format
    #
    # + tools - Array of tool definitions
    # + return - Array of Anthropic tool definitions as JSON
    private isolated function mapToAnthropicTools(ai:ChatCompletionFunctions[] tools) returns json[] {
        json[] anthropicTools = [];
        foreach ai:ChatCompletionFunctions tool in tools {
            map<json> schema = tool.parameters ?: {'type: "object", properties: {}};
            anthropicTools.push({
                name: tool.name,
                description: tool.description,
                input_schema: schema
            });
        }
        return anthropicTools;
    }

    # Maps a built-in model tool to the Anthropic API JSON format
    #
    # + tool - The built-in model tool to map
    # + return - JSON representation for the Anthropic API tools array or an error
    private isolated function mapBuiltInToolToJson(ai:BuiltInTool tool) returns json|ai:Error {
        if tool.name == WEB_SEARCH_TOOL_NAME {
            return self.mapWebSearchToolToJson(tool);
        }
        return self.mapCodeExecutionToolToJson(tool);
    }

    # Maps a web search tool to the Anthropic API JSON format
    #
    # + tool - The built-in model tool (expected to be a web search tool)
    # + return - JSON representation for the Anthropic API or an error
    private isolated function mapWebSearchToolToJson(ai:BuiltInTool tool) returns json|ai:Error {
        map<anydata>? configurations = tool.configurations;

        // Get version from configurations, or use default
        string toolType = DEFAULT_WEB_SEARCH_TOOL_TYPE;
        if configurations is map<anydata> {
            anydata configType = configurations["type"];
            if configType is string {
                toolType = configType;
            }
        }

        map<json> result = {"type": toolType, "name": WEB_SEARCH_TOOL_NAME};
        if configurations is () {
            return result;
        }
        anydata maxUses = configurations["max_uses"];
        if maxUses is int {
            result["max_uses"] = maxUses;
        }
        anydata allowedDomains = configurations["allowed_domains"];
        anydata blockedDomains = configurations["blocked_domains"];
        if allowedDomains is string[] && blockedDomains is string[] {
            return error ai:Error("'allowed_domains' and 'blocked_domains' are mutually exclusive in web search tool configuration");
        }
        
        if allowedDomains is string[] {
            result["allowed_domains"] = allowedDomains;
        }
        if blockedDomains is string[] {
            result["blocked_domains"] = blockedDomains;
        }
        anydata userLocation = configurations["user_location"];
        if userLocation is map<anydata> {
            map<json> location = {"type": "approximate"};
            anydata city = userLocation["city"];
            if city is string {
                location["city"] = city;
            }
            anydata region = userLocation["region"];
            if region is string {
                location["region"] = region;
            }
            anydata country = userLocation["country"];
            if country is string {
                location["country"] = country;
            }
            anydata timezone = userLocation["timezone"];
            if timezone is string {
                location["timezone"] = timezone;
            }
            result["user_location"] = location;
        }
        return result;
    }

    # Maps a code execution tool to the Anthropic API JSON format
    #
    # + tool - The built-in model tool (expected to be a code execution tool)
    # + return - JSON representation for the Anthropic API
    private isolated function mapCodeExecutionToolToJson(ai:BuiltInTool tool) returns json {
        map<anydata>? configurations = tool.configurations;

        // Get version from configurations, or use default
        string toolType = DEFAULT_CODE_EXECUTION_TOOL_TYPE;
        if configurations is map<anydata> {
            anydata configType = configurations["type"];
            if configType is string {
                toolType = configType;
            }
        }

        return {"type": toolType, "name": CODE_EXECUTION_TOOL_NAME};
    }
}

isolated function mapContentToFunctionCall(ContentBlock block) returns ai:FunctionCall|ai:LlmError {
    string? blockName = block.name;
    if blockName is () {
        return error ai:LlmError("Invalid or malformed name received in function call response.");
    }
    json inputJson = block?.input;
    map<json>?|error arguments = inputJson.cloneWithType();
    if arguments is error {
        return error ai:LlmError("Invalid or malformed arguments received in function call response.", arguments);
    }
    return {name: blockName, arguments};
}

isolated function getChatMessageStringContent(ai:Prompt|string prompt) returns string|ai:Error {
    if prompt is string {
        return prompt;
    }
    string[] & readonly strings = prompt.strings;
    anydata[] insertions = prompt.insertions;
    string promptStr = strings[0];
    foreach int i in 0 ..< insertions.length() {
        string str = strings[i + 1];
        anydata insertion = insertions[i];

        if insertion is ai:TextDocument|ai:TextChunk {
            promptStr += insertion.content + " " + str;
            continue;
        }

        if insertion is ai:TextDocument[] {
            foreach ai:TextDocument doc in insertion {
                promptStr += doc.content + " ";
            }
            promptStr += str;
            continue;
        }

        if insertion is ai:TextChunk[] {
            foreach ai:TextChunk doc in insertion {
                promptStr += doc.content + " ";
            }
            promptStr += str;
            continue;
        }

        if insertion is ai:Document {
            return error ai:Error("Only Text Documents are currently supported.");
        }

        promptStr += insertion.toString() + str;
    }
    return promptStr.trim();
}

isolated function convertMessageToJson(ai:ChatMessage[]|ai:ChatMessage messages) returns json|ai:Error {
    if messages is ai:ChatMessage[] {
        return messages.'map(msg => msg is ai:ChatUserMessage|ai:ChatSystemMessage ? check convertMessageToJson(msg) : msg);
    }
    if messages is ai:ChatUserMessage|ai:ChatSystemMessage {

    }
    return messages !is ai:ChatUserMessage|ai:ChatSystemMessage ? messages :
        {role: messages.role, content: check getChatMessageStringContent(messages.content), name: messages.name};
}
