// Copyright (c) 2025 WSO2 LLC (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/ai;
import ballerina/ai.observe;
import ballerina/http;
import ballerina/jballerina.java;

const DEFAULT_ANTHROPIC_SERVICE_URL = "https://api.anthropic.com/v1";
const DEFAULT_MAX_TOKEN_COUNT = 512;
const DEFAULT_TEMPERATURE = 0.7d;
const ANTHROPIC_API_VERSION = "2023-06-01";
# The smallest thinking budget Anthropic accepts for `enabled` extended thinking.
const MIN_THINKING_BUDGET_TOKENS = 1024;

# Provider is a client class that provides an interface for interacting with Anthropic Large Language Models.
public isolated client class ModelProvider {
    *ai:ModelProvider;
    private final http:Client AnthropicClient;
    private final string apiKey;
    private final string modelType;
    private final int maxTokens;
    private final decimal temperature;
    private final (readonly & ThinkingConfig)? thinkingConfig;

    # Initializes the Anthropic model with the given connection configuration and model configuration.
    #
    # + apiKey - The Anthropic API key
    # + modelType - The Anthropic model name
    # + apiVersion - The Anthropic API version (e.g., "2023-06-01")
    # + serviceUrl - The base URL of Anthropic API endpoint
    # + maxTokens - The upper limit for the number of tokens in the response generated by the model
    # + temperature - The temperature for controlling randomness in the model's output
    # + thinkingConfig - Extended thinking (reasoning) configuration; `()` leaves thinking off
    # + connectionConfig - Additional HTTP connection configuration
    # + return - `nil` on successful initialization; otherwise, returns an `ai:Error`
    public isolated function init(string apiKey,
            @display {label: "Model Type"} ANTHROPIC_MODEL_NAMES modelType,
            @display {label: "Service URL"} string serviceUrl = DEFAULT_ANTHROPIC_SERVICE_URL,
            @display {label: "Maximum Tokens"} int maxTokens = DEFAULT_MAX_TOKEN_COUNT,
            @display {label: "Temperature"} decimal temperature = DEFAULT_TEMPERATURE,
            @display {label: "Thinking Configuration"} ThinkingConfig? thinkingConfig = (),
            @display {label: "Connection Configuration"} *ConnectionConfig connectionConfig) returns ai:Error? {

        check validateThinkingConfig(thinkingConfig, maxTokens);

        // Convert ConnectionConfig to http:ClientConfiguration
        http:ClientConfiguration anthropicConfig = {
            httpVersion: connectionConfig.httpVersion,
            http1Settings: connectionConfig.http1Settings ?: {},
            http2Settings: connectionConfig?.http2Settings ?: {},
            timeout: connectionConfig.timeout,
            forwarded: connectionConfig.forwarded,
            poolConfig: connectionConfig?.poolConfig,
            cache: connectionConfig?.cache ?: {},
            compression: connectionConfig.compression,
            circuitBreaker: connectionConfig?.circuitBreaker,
            retryConfig: connectionConfig?.retryConfig,
            responseLimits: connectionConfig?.responseLimits ?: {},
            secureSocket: connectionConfig?.secureSocket,
            proxy: connectionConfig?.proxy,
            validation: connectionConfig.validation
        };

        http:Client|error httpClient = new http:Client(serviceUrl, anthropicConfig);
        if httpClient is error {
            return error ai:Error("Failed to initialize Anthropic Model", httpClient);
        }

        self.AnthropicClient = httpClient;
        self.apiKey = apiKey;
        self.modelType = modelType;
        self.maxTokens = maxTokens;
        self.temperature = temperature;
        self.thinkingConfig = thinkingConfig.cloneReadOnly();
    }

    # Applies this provider's extended-thinking settings to a request payload.
    #
    # + requestPayload - The request payload to mutate in place
    private isolated function applyThinkingConfig(map<json> requestPayload) {
        applyThinkingConfig(requestPayload, self.thinkingConfig, self.temperature);
    }

    # Uses Anthropic API to generate a response
    # + messages - List of chat messages or a user message
    # + tools - Tool definitions to be used for the tool call
    # + stop - Stop sequence to stop the completion (not used in this implementation)
    # + return - Chat response or an error in case of failures
    isolated remote function chat(ai:ChatMessage[]|ai:ChatUserMessage messages, ai:ChatCompletionFunctions[] tools = [], string? stop = ())
        returns ai:ChatAssistantMessage|ai:Error {
        observe:ChatSpan span = observe:createChatSpan(self.modelType);
        span.addProvider("anthropic");
        span.addTemperature(self.temperature);
        json|ai:Error inputMessage = convertMessageToJson(messages);
        if inputMessage is json {
            span.addInputMessages(inputMessage);
        }

        // Map messages to Anthropic format
        AnthropicMessage[]|ai:Error anthropicMessages = self.mapToAnthropicMessages(messages);
        if anthropicMessages is ai:Error {
            span.close(anthropicMessages);
            return anthropicMessages;
        }

        // Prepare request payload
        map<json> requestPayload = {
            model: self.modelType,
            max_tokens: self.maxTokens,
            messages: anthropicMessages
        };
        self.applyThinkingConfig(requestPayload);

        if stop is string {
            span.addStopSequence(stop);
            requestPayload["stop_sequences"] = [stop];
        }

        // If tools are provided, add them to the request
        if tools.length() > 0 {
            span.addTools(tools);
            requestPayload["tools"] = self.mapToAnthropicTools(tools);
        }

        // Send request to Anthropic API with proper headers
        map<string> headers = {
            "x-api-key": self.apiKey,
            "anthropic-version": ANTHROPIC_API_VERSION,
            "content-type": "application/json"
        };

        AnthropicApiResponse|error anthropicResponse = self.AnthropicClient->/messages.post(requestPayload, headers);
        if anthropicResponse is error {
            ai:Error err = error ai:LlmInvalidResponseError("Unexpected response format from Anthropic API", anthropicResponse);
            span.close(err);
            return err;
        }

        span.addResponseId(anthropicResponse.id);
        span.addInputTokenCount(anthropicResponse.usage.input_tokens);
        span.addOutputTokenCount(anthropicResponse.usage.output_tokens);
        span.addFinishReason(anthropicResponse.stop_reason);

        ai:ChatAssistantMessage|ai:Error response = self.getAssistantMessage(anthropicResponse);
        if response is ai:Error {
            span.close(response);
            return response;
        }
        span.addOutputMessages(response);
        span.addOutputType(observe:TEXT);
        span.close();
        return response;
    }

    # Uses the Anthropic API to generate a streaming response.
    # + messages - List of chat messages or a user message
    # + tools - Tool definitions to be used for the tool call
    # + stop - Stop sequence to stop the completion
    # + return - A stream of normalized chat message chunks, or an error in case of failures
    isolated remote function chatAsStream(
            ai:ChatMessage[]|ai:ChatUserMessage messages,
            ai:ChatCompletionFunctions[] tools = [],
            string? stop = ())
            returns stream<ai:ChatMessageChunk, ai:Error?>|ai:Error {
        observe:ChatSpan span = observe:createChatSpan(self.modelType);
        span.addProvider("anthropic");
        if self.thinkingConfig !is EnabledThinking|AdaptiveThinking {
            // Temperature is only sent when extended thinking is inactive; recording it
            // otherwise would report a value the request never carried.
            span.addTemperature(self.temperature);
        }
        json|ai:Error inputMessage = convertMessageToJson(messages);
        if inputMessage is json {
            span.addInputMessages(inputMessage);
        }

        AnthropicMessage[]|ai:Error anthropicMessages = self.mapToAnthropicMessages(messages);
        if anthropicMessages is ai:Error {
            span.close(anthropicMessages);
            return anthropicMessages;
        }

        map<json> requestPayload = {
            model: self.modelType,
            max_tokens: self.maxTokens,
            messages: anthropicMessages,
            'stream: true
        };
        self.applyThinkingConfig(requestPayload);

        if stop is string {
            span.addStopSequence(stop);
            requestPayload["stop_sequences"] = [stop];
        }

        if tools.length() > 0 {
            span.addTools(tools);
            requestPayload["tools"] = self.mapToAnthropicTools(tools);
        }

        map<string> headers = {
            "x-api-key": self.apiKey,
            "anthropic-version": ANTHROPIC_API_VERSION,
            "content-type": "application/json"
        };

        return self.openChunkStream(requestPayload, headers, span);
    }

    # Sends a streaming chat request to the model using the given prompt and streams back
    # the generated answer as text fragments. The request is built from the prompt the same
    # way as for `generate` (text, image and file content parts).
    #
    # + prompt - The prompt to use in the chat request
    # + return - A stream of text fragments, or an error if generation fails
    isolated remote function generateAsStream(ai:Prompt prompt) returns stream<string, ai:Error?>|ai:Error {
        observe:GenerateContentSpan span = observe:createGenerateContentSpan(self.modelType);
        span.addProvider("anthropic");
        if self.thinkingConfig !is EnabledThinking|AdaptiveThinking {
            // Temperature is only sent when extended thinking is inactive; recording it
            // otherwise would report a value the request never carried.
            span.addTemperature(self.temperature);
        }

        DocumentContentPart[]|ai:Error content = generateChatCreationContent(prompt);
        if content is ai:Error {
            span.close(content);
            return content;
        }

        map<json>[] messages = [{role: ai:USER, "content": content}];
        span.addInputMessages(messages);

        map<json> requestPayload = {
            model: self.modelType,
            max_tokens: self.maxTokens,
            messages,
            'stream: true
        };
        self.applyThinkingConfig(requestPayload);

        map<string> headers = {
            "x-api-key": self.apiKey,
            "anthropic-version": ANTHROPIC_API_VERSION,
            "content-type": "application/json"
        };

        stream<ai:ChatMessageChunk, ai:Error?>|ai:Error chunks = self.openChunkStream(requestPayload, headers, span);
        if chunks is ai:Error {
            return chunks;
        }
        return new stream<string, ai:Error?>(new ChunkTextIterator(chunks));
    }

    // Opens the SSE stream for `requestPayload`. The span is closed here if the connection
    // fails to open, and by the returned stream's iterator otherwise.
    private isolated function openChunkStream(map<json> requestPayload, map<string> headers, observe:ChatSpan|observe:GenerateContentSpan span)
            returns stream<ai:ChatMessageChunk, ai:Error?>|ai:Error {
        stream<http:SseEvent, error?>|error sseStream =
            self.AnthropicClient->/messages.post(requestPayload, headers);
        if sseStream is error {
            ai:Error err = error ai:LlmConnectionError(
                    string `Error while connecting to the model: ${sseStream.message()}`);
            closeStreamSpan(span, err);
            return err;
        }

        // Assign to an explicitly typed local first: `new (..)` cannot infer the stream
        // type when the function's return type is a union (`stream<...>|ai:Error`).
        stream<ai:ChatMessageChunk, ai:Error?> chunkStream = new (new AnthropicChunkIterator(sseStream, span));
        return chunkStream;
    }

    private isolated function getAssistantMessage(AnthropicApiResponse anthropicResponse) returns ai:ChatAssistantMessage|ai:Error {
        string? content = ();
        ai:FunctionCall[] toolCalls = [];
        foreach ContentBlock block in anthropicResponse.content {
            string blockType = block.'type;
            if blockType == "tool_use" {
                toolCalls.push(check mapContentToFunctionCall(block));
            } else if blockType == "text" {
                content = block.text;
            }
        }
        return {role: ai:ASSISTANT, toolCalls: toolCalls == [] ? () : toolCalls, content};
    }

    # Sends a chat request to the model and generates a value that belongs to the type
    # corresponding to the type descriptor argument.
    #
    # + prompt - The prompt to use in the chat messages
    # + td - Type descriptor specifying the expected return type format
    # + return - Generates a value that belongs to the type, or an error if generation fails
    isolated remote function generate(ai:Prompt prompt, @display {label: "Expected type"} typedesc<anydata> td = <>)
                    returns td|ai:Error = @java:Method {
        'class: "io.ballerina.lib.ai.anthropic.Generator"
    } external;

    # Converts standard ai:ChatMessage array to Anthropic's message format
    #
    # + messages - List of chat messages or a user message
    # + return - return value description
    private isolated function mapToAnthropicMessages(ai:ChatMessage[]|ai:ChatUserMessage messages)
    returns AnthropicMessage[]|ai:Error {
        AnthropicMessage[] anthropicMessages = [];
        if messages is ai:ChatUserMessage {
            anthropicMessages.push({
                role: ai:USER,
                content: check getChatMessageStringContent(messages.content)
            });
            return anthropicMessages;
        }

        foreach ai:ChatMessage message in messages {
            if message is ai:ChatUserMessage {
                anthropicMessages.push({
                    role: ai:USER,
                    content: check getChatMessageStringContent(message.content)
                });
            } else if message is ai:ChatSystemMessage {
                // Add a user message containing the system prompt
                string content = check getChatMessageStringContent(message.content);
                anthropicMessages.push({
                    role: ai:USER,
                    content: string `<system>${content}</system>\n\n`
                });
            } else if message is ai:ChatAssistantMessage && message.content is string {
                anthropicMessages.push({
                    role: ai:ASSISTANT,
                    content: message.content ?: ""
                });
            } else if message is ai:ChatFunctionMessage && message.content is string {
                // Include function results as user messages with special formatting
                anthropicMessages.push({
                    role: ai:USER,
                    content: string `<function_results>\nFunction: ${message.name}\n`
                        + string `Output: ${message.content ?: ""}\n</function_results>`
                });
            }
        }
        return anthropicMessages;
    }

    # Maps ai:ChatCompletionFunctions to Anthropic's tool format
    #
    # + tools - Array of tool definitions
    # + return - Array of Anthropic tool definitions
    private isolated function mapToAnthropicTools(ai:ChatCompletionFunctions[] tools) returns AnthropicTool[] {
        AnthropicTool[] anthropicTools = [];

        foreach ai:ChatCompletionFunctions tool in tools {
            map<json> schema = tool.parameters ?: {'type: "object", properties: {}};

            // Create Anthropic tool with input_schema instead of parameters
            AnthropicTool AnthropicTool = {
                name: tool.name,
                description: tool.description,
                input_schema: schema
            };

            anthropicTools.push(AnthropicTool);
        }

        return anthropicTools;
    }
}

# Iterator that converts Anthropic's Server-Sent Event stream into a stream of normalized
# `ai:ChatMessageChunk` values. Anthropic's stream is stateful: the message id and
# input-token count arrive once on `message_start`, so they are captured and carried onto
# subsequent chunks. Each event is parsed and mapped via `toAiChunk`; non-emitting events
# (`ping`, `content_block_stop`, `message_start`) are skipped.
#
# A generation can fail *after* the stream has opened: Anthropic then sends an `error` event
# (or simply stops sending) while the transport still reports success. Both cases surface as
# an `ai:Error` rather than a short, clean-looking result, so a caller can never mistake a
# truncated answer for a complete one.
#
# The errors raised here deliberately carry no `cause`, and fold the underlying detail into
# their message instead: a query expression (`from ... in stream do`) - the idiomatic way to
# consume a stream - propagates an error's *cause* rather than the error itself, so a wrapped
# error would reach the caller as an opaque `FromJsonStringError` and the explanation would
# be lost.
#
# The response id, token usage and finish reason are reported to the span, which is closed
# exactly once: on `message_stop`, on exhaustion, on the first error, or when the caller
# closes the stream early.
class AnthropicChunkIterator {
    private final stream<http:SseEvent, error?> sseStream;
    private final observe:ChatSpan|observe:GenerateContentSpan span;
    private string? id = ();
    private boolean completed = false;

    isolated function init(stream<http:SseEvent, error?> sseStream, observe:ChatSpan|observe:GenerateContentSpan span) {
        self.sseStream = sseStream;
        self.span = span;
    }

    public isolated function next() returns record {|ai:ChatMessageChunk value;|}|ai:Error? {
        if self.isCompleted() {
            return ();
        }
        while true {
            record {|http:SseEvent value;|}|error? nextEvent = self.sseStream.next();
            if nextEvent is () {
                // The transport ended without a `message_stop`, so the answer is truncated.
                return self.failWith(error ai:LlmInvalidResponseError(
                        "Model stream ended before the response was complete"));
            }
            if nextEvent is error {
                return self.failWith(error ai:LlmError(
                        string `Error while reading the model stream: ${nextEvent.message()}`));
            }

            http:SseEvent sseEvent = nextEvent.value;
            string? event = sseEvent.event;
            string? rawData = sseEvent.data;
            if event is () || rawData is () {
                continue;
            }
            if event == "message_stop" {
                self.complete();
                return ();
            }

            json|error payload = rawData.fromJsonString();
            if payload is error {
                return self.failWith(error ai:LlmInvalidResponseError(
                        string `Invalid or malformed chunk received from the model: ${payload.message()}`));
            }

            if event == "error" {
                return self.failWith(toStreamError(payload));
            }

            if event == "message_start" {
                self.recordMessageStart(payload);
                continue;
            }
            if event == "message_delta" {
                self.recordMessageDelta(payload);
            }

            ai:ChatMessageChunk?|error chunk = toAiChunk(event, payload, self.id);
            if chunk is error {
                return self.failWith(error ai:LlmInvalidResponseError(
                        string `Invalid or malformed '${event}' chunk received from the model: ${chunk.message()}`));
            }
            if chunk is ai:ChatMessageChunk {
                return {value: chunk};
            }
        }
    }

    public isolated function close() returns ai:Error? {
        self.complete();
        error? result = self.sseStream.close();
        if result is error {
            return error ai:LlmConnectionError("Error while closing the model stream", result);
        }
        return ();
    }

    // Captures the message id, and reports the response id and input-token count carried by
    // `message_start` to the span. Malformed payloads are ignored; `message_start` never
    // fails the stream since it carries nothing essential to the caller.
    private isolated function recordMessageStart(json payload) {
        StreamMessageStart|error messageStart = payload.cloneWithType();
        if messageStart is error {
            return;
        }
        self.id = messageStart.message.id;
        recordStreamResponseId(self.span, messageStart.message.id);
        recordStreamInputTokenCount(self.span, messageStart.message.usage.input_tokens);
    }

    // Reports the cumulative output-token count and raw finish reason carried by
    // `message_delta` to the span. Malformed payloads are ignored here; `toAiChunk` surfaces
    // the parse error to the caller.
    private isolated function recordMessageDelta(json payload) {
        StreamMessageDelta|error messageDelta = payload.cloneWithType();
        if messageDelta is error {
            return;
        }
        recordStreamOutputTokenCount(self.span, messageDelta.usage.output_tokens);
        string? stopReason = messageDelta.delta.stop_reason;
        if stopReason is string {
            recordStreamFinishReason(self.span, stopReason);
        }
    }

    private isolated function isCompleted() returns boolean {
        lock {
            return self.completed;
        }
    }

    # Marks the stream finished and closes the observability span, exactly once.
    private isolated function complete() {
        if self.markCompleted() {
            return;
        }
        closeStreamSpan(self.span, ());
    }

    # Marks the stream finished, closes the span against `err`, and returns `err` so callers
    # can `return self.failWith(...)` on every terminal error path.
    #
    # + err - The error that ended the stream
    # + return - The same error
    private isolated function failWith(ai:Error err) returns ai:Error {
        if self.markCompleted() {
            return err;
        }
        closeStreamSpan(self.span, err);
        return err;
    }

    # Marks the stream completed.
    #
    # + return - Whether the stream was already marked completed before this call
    private isolated function markCompleted() returns boolean {
        lock {
            boolean wasCompleted = self.completed;
            self.completed = true;
            return wasCompleted;
        }
    }
}

# Maps an Anthropic `error` streaming event onto an `ai:Error`, preserving the API's own
# error type and message so the caller sees why generation stopped.
#
# + payload - The raw `error` event payload
# + return - The corresponding `ai:Error`
isolated function toStreamError(json payload) returns ai:Error {
    StreamError|error streamError = payload.cloneWithType();
    if streamError !is StreamError {
        return error ai:LlmError("Model stream failed with an unrecognized error event");
    }
    StreamErrorDetail? detail = streamError.'error;
    if detail is () {
        return error ai:LlmError("Model stream failed");
    }
    string message = detail.message ?: "Model stream failed";
    string? errorType = detail.'type;
    if errorType is string {
        return error ai:LlmError(string `Model stream failed with '${errorType}': ${message}`);
    }
    return error ai:LlmError(message);
}

// Calling a method through the `ChatSpan|GenerateContentSpan` union does not resolve via
// their common `LlmSpan` interface (a cross-module object-type-inclusion limitation), so
// each of these narrows to the concrete type before delegating.

isolated function closeStreamSpan(observe:ChatSpan|observe:GenerateContentSpan span, ai:Error? err) {
    if span is observe:ChatSpan {
        span.close(err);
    } else if span is observe:GenerateContentSpan {
        span.close(err);
    }
}

isolated function recordStreamResponseId(observe:ChatSpan|observe:GenerateContentSpan span, string id) {
    if span is observe:ChatSpan {
        span.addResponseId(id);
    } else if span is observe:GenerateContentSpan {
        span.addResponseId(id);
    }
}

isolated function recordStreamInputTokenCount(observe:ChatSpan|observe:GenerateContentSpan span, int count) {
    if span is observe:ChatSpan {
        span.addInputTokenCount(count);
    } else if span is observe:GenerateContentSpan {
        span.addInputTokenCount(count);
    }
}

isolated function recordStreamOutputTokenCount(observe:ChatSpan|observe:GenerateContentSpan span, int count) {
    if span is observe:ChatSpan {
        span.addOutputTokenCount(count);
    } else if span is observe:GenerateContentSpan {
        span.addOutputTokenCount(count);
    }
}

isolated function recordStreamFinishReason(observe:ChatSpan|observe:GenerateContentSpan span, string reason) {
    if span is observe:ChatSpan {
        span.addFinishReason(reason);
        span.addOutputType(observe:TEXT);
    } else if span is observe:GenerateContentSpan {
        span.addFinishReason(reason);
        span.addOutputType(observe:TEXT);
    }
}

# Projects a `ai:ChatMessageChunk` stream onto its answer text, yielding each non-empty
# `content` fragment and skipping tool-call, reasoning, and finish-only chunks. Backs
# `generateAsStream`; closing it closes the underlying chunk stream.
class ChunkTextIterator {
    private final stream<ai:ChatMessageChunk, ai:Error?> chunks;

    isolated function init(stream<ai:ChatMessageChunk, ai:Error?> chunks) {
        self.chunks = chunks;
    }

    public isolated function next() returns record {|string value;|}|ai:Error? {
        while true {
            record {|ai:ChatMessageChunk value;|}|ai:Error? next = self.chunks.next();
            if next !is record {|ai:ChatMessageChunk value;|} {
                return next;
            }
            string? content = next.value.content;
            if content is string && content.length() > 0 {
                return {value: content};
            }
        }
    }

    public isolated function close() returns ai:Error? {
        return self.chunks.close();
    }
}

# Applies extended-thinking settings to a request payload: adds the `thinking` object when
# configured, and sends `temperature` only when thinking is not active, because Anthropic
# requires the default temperature with `enabled`/`adaptive` thinking.
#
# Shared by every request path (`chat`, `chatAsStream`, `generateAsStream`, and `generate`) so
# that a configured `thinkingConfig` cannot silently apply to some of them and not others.
#
# + requestPayload - The request payload to mutate in place
# + thinkingConfig - The configured thinking settings, or `()` when thinking is off
# + temperature - The temperature to send when thinking is not active
isolated function applyThinkingConfig(map<json> requestPayload,
        (readonly & ThinkingConfig)? thinkingConfig, decimal temperature) {
    if thinkingConfig is ThinkingConfig {
        requestPayload["thinking"] = thinkingConfig;
    }
    if thinkingConfig !is EnabledThinking|AdaptiveThinking {
        requestPayload["temperature"] = temperature;
    }
}

# Validates an extended-thinking configuration against the request's token budget.
#
# Anthropic requires `budget_tokens` to be at least 1024 and strictly less than the
# request's `max_tokens`. Checking at construction turns what would otherwise be an opaque
# HTTP failure on every subsequent call into an immediate, actionable error.
#
# + thinkingConfig - The configured thinking settings, or `()` when thinking is off
# + maxTokens - The configured upper bound on response tokens
# + return - An `ai:Error` describing the conflict, or `()` when the configuration is usable
isolated function validateThinkingConfig(ThinkingConfig? thinkingConfig, int maxTokens) returns ai:Error? {
    if thinkingConfig !is EnabledThinking {
        return ();
    }
    int budget = thinkingConfig.budget_tokens;
    if budget < MIN_THINKING_BUDGET_TOKENS {
        return error ai:Error(string `Invalid thinking configuration: 'budget_tokens' must be at least ` +
            string `${MIN_THINKING_BUDGET_TOKENS}, but found ${budget}.`);
    }
    if budget >= maxTokens {
        return error ai:Error(string `Invalid thinking configuration: 'budget_tokens' (${budget}) must be ` +
            string `less than 'maxTokens' (${maxTokens}). Increase 'maxTokens' above the thinking budget.`);
    }
    return ();
}

isolated function mapContentToFunctionCall(ContentBlock block) returns ai:FunctionCall|ai:LlmError {
    string? blockName = block.name;
    if blockName is () {
        return error ai:LlmError("Invalid or malformed name received in function call response.");
    }
    json inputJson = block?.input;
    map<json>?|error arguments = inputJson.cloneWithType();
    if arguments is error {
        return error ai:LlmError("Invalid or malformed arguments received in function call response.", arguments);
    }
    return {name: blockName, arguments};
}

isolated function getChatMessageStringContent(ai:Prompt|string prompt) returns string|ai:Error {
    if prompt is string {
        return prompt;
    }
    string[] & readonly strings = prompt.strings;
    anydata[] insertions = prompt.insertions;
    string promptStr = strings[0];
    foreach int i in 0 ..< insertions.length() {
        string str = strings[i + 1];
        anydata insertion = insertions[i];

        if insertion is ai:TextDocument|ai:TextChunk {
            promptStr += insertion.content + " " + str;
            continue;
        }

        if insertion is ai:TextDocument[] {
            foreach ai:TextDocument doc in insertion {
                promptStr += doc.content + " ";
            }
            promptStr += str;
            continue;
        }

        if insertion is ai:TextChunk[] {
            foreach ai:TextChunk doc in insertion {
                promptStr += doc.content + " ";
            }
            promptStr += str;
            continue;
        }

        if insertion is ai:Document {
            return error ai:Error("Only Text Documents are currently supported.");
        }

        promptStr += insertion.toString() + str;
    }
    return promptStr.trim();
}

isolated function convertMessageToJson(ai:ChatMessage[]|ai:ChatMessage messages) returns json|ai:Error {
    if messages is ai:ChatMessage[] {
        return messages.'map(msg => msg is ai:ChatUserMessage|ai:ChatSystemMessage ? check convertMessageToJson(msg) : msg);
    }
    if messages is ai:ChatUserMessage|ai:ChatSystemMessage {

    }
    return messages !is ai:ChatUserMessage|ai:ChatSystemMessage ? messages :
        {role: messages.role, content: check getChatMessageStringContent(messages.content), name: messages.name};
}
